name: CI Build
on: 
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Start containers
        run: docker-compose -f docker-compose.yaml up -d
      - name: Build project with Maven in Quarkus
        run: mvn compile
      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose.yaml down
