name: CI Build
on: 
  push:
    branches: [ main ]
  workflow_dispatch:    
env:
  MVN_TEST_COVERAGE: '-Dskip.code.coverage=false'  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
           distribution: 'temurin'
           java-version: '11'
           cache: 'maven'
      - name: Build project with Maven in Quarkus
        run: mvn compile
